name: CD - Build & Deploy

on:
  push:
    branches:
      - main # Triggers when a PR is merged into main

jobs:
  setup:
    name: Install & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Read Node.js Version
        id: node_version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Enable Corepack # Ensures the correct version of yarn is used
        run: corepack enable

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"

      - name: Authenticate NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.GREEN_FLASH_NPM_TOKEN }}" > ~/.npmrc

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Upload Workspace as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: repo-artifact
          path: .
          retention-days: 1

  library:
    name: Publish to NPM registry
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Build Project
        run: yarn build

      - name: Download Repository Artifact
        uses: actions/download-artifact@v4
        with:
          name: repo-artifact

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GREEN_FLASH_NPM_TOKEN }}

  storybook:
    name: Deploy storybook to Cloudflare
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Download Repository Artifact
        uses: actions/download-artifact@v4
        with:
          name: repo-artifact

      - name: Build Storybook
        run: yarn build-storybook

      - name: Deploy storybook
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.GREEN_FLASH_CLOUDFLARE_API_TOKEN }}
          command: pages deploy ./storybook-static --project-name=react-hook-primitives-storybook
