name: CD - Deploy | Storybook

on:
  push:
    branches:
      - main # Triggers when a PR is merged into main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Read Node.js Version
        id: node_version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_ENV

      - name: Enable Corepack # Ensures the correct version of yarn is used
        run: corepack enable

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "yarn"

      - name: Authenticate NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.GREEN_FLASH_NPM_TOKEN }}" > ~/.npmrc

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build Storybook
        run: yarn build-storybook

      - name: Deploy storybook
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.GREEN_FLASH_CLOUDFLARE_API_TOKEN }}
          command: pages deploy ./storybook-static --project-name=react-hook-primitives-storybook
